//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstoqueProduto
    {
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public Nullable<int> IdOrdemCompra { get; set; }
        public Nullable<int> IdOrdemServico { get; set; }
        public System.DateTime DataMovimentacao { get; set; }
        public int IdHistorico { get; set; }
        public decimal ValorUnitario { get; set; }
    
        public virtual HistoricoEstoque HistoricoEstoque { get; set; }
        public virtual OrdemCompra OrdemCompra { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
