//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSaida
    {
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public int IdSsaida { get; set; }
        public int Valor { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Saida Saida { get; set; }
    }
}
