//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPagamento
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int Parcelas { get; set; }
        public decimal Taxa { get; set; }
        public int PrazoPagamento { get; set; }
    }
}
