//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloAparelho
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string NumeroModelo { get; set; }
        public int IdTipoAparelho { get; set; }
        public int IdMarca { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual TipoAparelho TipoAparelho { get; set; }
    }
}
