//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoHistorico
    {
        public int Id { get; set; }
        public string Notas { get; set; }
        public System.DateTime Data { get; set; }
        public int IdOrdemServico { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual OrdemServico OrdemServico { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
