//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecoServico
    {
        public int Id { get; set; }
        public int IdServico { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
        public decimal PrecoDinheiro { get; set; }
        public Nullable<decimal> PrecoDebito { get; set; }
        public Nullable<decimal> PrecoCredito { get; set; }
    
        public virtual Servico Servico { get; set; }
    }
}
