//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.EstoqueProduto = new HashSet<EstoqueProduto>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> QtdeMinima { get; set; }
        public string Sku { get; set; }
        public int IdTipoProduto { get; set; }
        public int IdModeloAparelho { get; set; }
        public Nullable<int> IdCor { get; set; }
    
        public virtual Cor Cor { get; set; }
        public virtual ModeloAparelho ModeloAparelho { get; set; }
        public virtual TipoProduto TipoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstoqueProduto> EstoqueProduto { get; set; }
    }
}
