//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrice
    {
        public int Id { get; set; }
        public int IdService { get; set; }
        public System.DateTime Updated { get; set; }
        public decimal Price { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
