//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsertoPraVoce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transacao()
        {
            this.TransacaoItem = new HashSet<TransacaoItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataTransacao { get; set; }
        public string Descricao { get; set; }
        public decimal ValorBruto { get; set; }
        public int IdCategoriaTransacao { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<bool> PagamentoRecorrente { get; set; }
        public string Detalhes { get; set; }
        public int IdConta { get; set; }
        public Nullable<int> IdOrdemServico { get; set; }
        public Nullable<int> IdOrdemCompra { get; set; }
        public int Parcelas { get; set; }
        public System.DateTime DataModificacao { get; set; }
        public int IdSubCategoriaTransacao { get; set; }
    
        public virtual CategoriaTransacao CategoriaTransacao { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Conta Conta { get; set; }
        public virtual OrdemCompra OrdemCompra { get; set; }
        public virtual OrdemServico OrdemServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransacaoItem> TransacaoItem { get; set; }
        public virtual CategoriaTransacao CategoriaTransacao1 { get; set; }
    }
}
